### ISSUE TITLE
js:test erroring locally Win10

### ISSUE THREAD

**Issue by jrgleason** [cpettitt/dagre-d3#212]
Running gulp dist gives me...

```
[11:30:28] 'core-js:test' errored after 12 s
[11:30:28] Error: 1
    at formatError (C:\Users\..\AppData\Roaming\nvm\v0.12.9\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\..\AppData\Roaming\nvm\v0.12.9\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (C:\tmp\d3\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at C:\tmp\d3\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (C:\tmp\d3\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\tmp\d3\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
....
[11:30:29] 'js:test' errored after 7.12 s
[11:30:29] Error: 1
    at formatError (C:\Users\...\AppData\Roaming\nvm\v0.12.9\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\...\AppData\Roaming\nvm\v0.12.9\node_modules\gulp\bin\gulp.js:195:15)    
```

**Comment by jrgleason** [comment]
It appears to be a Karma issue so I guess I should close this. In case someone else comes across it has to do with removing the browsers.

commenting this out fixes it...

    webServer.close(function () {
        clearTimeout(closeTimeout)
        // removeAllListeners()
      })
