### ISSUE TITLE
Uncaught TypeError: elem.getTransformToElement is not a function

### ISSUE THREAD

**Issue by arnold-jr** [cpettitt/dagre-d3#282]
I'm loving dagre, but I've run across this issue in Chrome:

```
Uncaught TypeError: elem.getTransformToElement is not a function
    at getCoords (http://www.samsarin.com/project/dagre-d3/v0.4.10/dagre-d3.js:271:21)
    at http://www.samsarin.com/project/dagre-d3/v0.4.10/dagre-d3.js:286:72
    at Array.map (native)
    at SVGPathElement.<anonymous> (http://www.samsarin.com/project/dagre-d3/v0.4.10/dagre-d3.js:286:48)
    at SVGPathElement.o (http://d3js.org/d3.v3.min.js:1:2522)
    at http://d3js.org/d3.v3.min.js:3:15103
    at Y (http://d3js.org/d3.v3.min.js:1:4505)
    at Array.Co.each (http://d3js.org/d3.v3.min.js:3:15078)
    at Array.Co.attr (http://d3js.org/d3.v3.min.js:3:11915)
    at enter (http://www.samsarin.com/project/dagre-d3/v0.4.10/dagre-d3.js:283:6)
```

My script creates clusters following the clusters example, so pretty simple. I get no such error in Firefox.

Thanks!

**Comment by HarveyZ-CN** [comment]
Please try dagre-d3-0.4.17, which has fixed this issue
